CREATE TABLE NR_SAFETY_ITRACKER_F
  (
    "NDS_REF"              VARCHAR2(30 BYTE),
    "CURRENT_STATUS"       VARCHAR2(30 BYTE),
    "SRC_CREATED_BY"       VARCHAR2(255 BYTE),
    "INITIAL_REPORT_DATE"  DATE,
    "FINAL_REPORT_DATE"    DATE,
    "COMPLETE_DATE"        DATE,
    "PRINCIPAL_CONTRACTOR" VARCHAR2(255 BYTE),
    "SUB_CONTRACTOR"       VARCHAR2(255 BYTE),
    "LOCATION"             VARCHAR2(256 BYTE),
    "DAYS_LOST"            NUMBER(22,7),
    "EVENT_TYPE"           VARCHAR2(256 BYTE),
    "CLASSIFICATION"       VARCHAR2(255 BYTE),
    "SUB_CLASSIFICATION"   VARCHAR2(255 BYTE),
    "RECEPTOR"             VARCHAR2(255 BYTE),
    "EVENT_DESCRIPTION"    VARCHAR2(4000 BYTE),
    PROJECT_WID            NUMBER(10,0),
    REGION_WID             NUMBER(10,0),
    ROUTE_WID              NUMBER(10,0),
    PERIOD_WID             NUMBER(10,0),
    INCIDENT_DT_WID        NUMBER(10,0),
    "ROW_WID"              NUMBER(10,0) NOT NULL ENABLE,
    "CREATED_BY_WID"       NUMBER(10,0),
    "CHANGED_BY_WID"       NUMBER(10,0),
    "CREATED_ON_DT"        DATE,
    "CHANGED_ON_DT"        DATE,
    "W_INSERT_DT"          DATE,
    "W_UPDATE_DT"          DATE,
    "DATASOURCE_NUM_ID"    NUMBER(10,0) NOT NULL ENABLE,
    "ETL_PROC_WID"         NUMBER(10,0) NOT NULL ENABLE,
    "INTEGRATION_ID"       VARCHAR2(255 CHAR) NOT NULL ENABLE
  )
 
 
 
 CREATE UNIQUE INDEX "BIAPPS"."NR_SAFETY_ITRACKER_F_P1" ON "BIAPPS"."NR_SAFETY_ITRACKER_F"
  (
    "ROW_WID"
  )
  ;
CREATE UNIQUE INDEX "BIAPPS"."NR_SAFETY_ITRACKER_F_U1" ON "BIAPPS"."NR_SAFETY_ITRACKER_F"
  (
    "INTEGRATION_ID",DATASOURCE_NUM_ID
  )
  ; 
 