--------------------------------------------------------
--  DDL for Table NR_MFMA_STG
--------------------------------------------------------
CREATE TABLE "NR_MFMA_STG"
  (
    "PERIOD_NUM"                  NUMBER(10,0),
    "YEAR_NUM"                    NUMBER(10,0),
    "PROJECT_TITLE"               VARCHAR2(255 BYTE),
    "PROJECT_NO"                  VARCHAR2(30 BYTE),
    "STAGE"                       VARCHAR2(30 BYTE),
    "FUNDER"                      VARCHAR2(50 BYTE),
    "COST_CENTRE"                 VARCHAR2(30 BYTE),
    "ACCOUNT_CODE"                VARCHAR2(30 BYTE),
    "ROUTE"                       VARCHAR2(100 BYTE),
    "ROUTE_PERCENTAGE"            NUMBER(10,0),
    "CURRENT_AUTHORITY"           NUMBER(25,7),
    "AFC_APPROVED_STAGES"         NUMBER(25,7),
    "AFC_ALL_STAGES"              NUMBER(25,7),
    "CA_AFC_ALL"                  NUMBER(22,7),
    "COWD_PROJECT_TO_DATE"        NUMBER(22,7),
    "COWD_AFC_ALL"                NUMBER(22,7),
    "PERIOD_ACTUAL"               NUMBER(22,7),
    "PERIOD_BUDGET"               NUMBER(22,7),
    "PERIOD_VARIANCE"             NUMBER(22,7),
    "YTD_ACTUAL"                  NUMBER(22,7),
    "YTD_BUDGET"                  NUMBER(22,7),
    "YTD_VARIANCE"                NUMBER(22,7),
    "FY_FORECAST"                 NUMBER(22,7),
    "FY_BUDGET"                   NUMBER(22,7),
    "FY_VARIANCE"                 NUMBER(22,7),
    "CHANGE_PREVIOUS_FORECAST"    NUMBER(22,7),
    "FORECAST_AT_PREVIOUS_PERIOD" NUMBER(22,7),
    "DELIVERY_GROUP"              VARCHAR2(50 BYTE),
    "SPONSORING_GROUP"            VARCHAR2(50 BYTE),
    "FUNDING_CATEGORY"            VARCHAR2(50 BYTE),
    "ASSET_CATEGORY"              VARCHAR2(50 BYTE),
    "MFMA_PROJECT"                VARCHAR2(3 BYTE),
    "MULTIASSET"                  VARCHAR2(1 BYTE),
    "MULTIFUNDING"                VARCHAR2(1 BYTE),
    "NATIONAL_PROGRAMME"          VARCHAR2(30 BYTE),
    "LOCAL_PROGRAMME"             VARCHAR2(30 BYTE),
    "TERRITORY"                   VARCHAR2(50 BYTE),
    "ASSET_GROUP"                 VARCHAR2(50 BYTE),
    "PROGRAMME_MANAGER"           VARCHAR2(150 BYTE),
    "PROJECT_MANAGER"             VARCHAR2(150 BYTE),
    "PERIOD_1"                    NUMBER(22,7),
    "PERIOD_2"                    NUMBER(22,7),
    "PERIOD_3"                    NUMBER(22,7),
    "PERIOD_4"                    NUMBER(22,7),
    "PERIOD_5"                    NUMBER(22,7),
    "PERIOD_6"                    NUMBER(22,7),
    "PERIOD_7"                    NUMBER(22,7),
    "PERIOD_8"                    NUMBER(22,7),
    "PERIOD_9"                    NUMBER(22,7),
    "PERIOD_10"                   NUMBER(22,7),
    "PERIOD_11"                   NUMBER(22,7),
    "PERIOD_12"                   NUMBER(22,7),
    "PERIOD_13"                   NUMBER(22,7),
    "NEXT_PERIOD_1"               NUMBER(22,7),
    "NEXT_PERIOD_2"               NUMBER(22,7),
    "NEXT_PERIOD_3"               NUMBER(22,7),
    "NEXT_PERIOD_4"               NUMBER(22,7),
    "NEXT_PERIOD_5"               NUMBER(22,7),
    "NEXT_PERIOD_6"               NUMBER(22,7),
    "NEXT_PERIOD_7"               NUMBER(22,7),
    "NEXT_PERIOD_8"               NUMBER(22,7),
    "NEXT_PERIOD_9"               NUMBER(22,7),
    "NEXT_PERIOD_10"              NUMBER(22,7),
    "NEXT_PERIOD_11"              NUMBER(22,7),
    "NEXT_PERIOD_12"              NUMBER(22,7),
    "NEXT_PERIOD_13"              NUMBER(22,7),
    "CONTROL_PERIOD_Y1"           NUMBER(22,7),
    "CONTROL_PERIOD_Y2"           NUMBER(22,7),
    "CONTROL_PERIOD_Y3"           NUMBER(22,7),
    "CONTROL_PERIOD_Y4"           NUMBER(22,7),
    "CONTROL_PERIOD_Y5"           NUMBER(22,7),
    "NEXT_CONTROL_PERIOD_Y1"      NUMBER(22,7),
    "NEXT_CONTROL_PERIOD_Y2"      NUMBER(22,7),
    "NEXT_CONTROL_PERIOD_Y3"      NUMBER(22,7),
    "NEXT_CONTROL_PERIOD_Y4"      NUMBER(22,7),
    "NEXT_CONTROL_PERIOD_Y5"      NUMBER(22,7),
    "CONTROL_PERIOD_PREV"         NUMBER(22,7),
    "CONTROL_PERIOD_NEXT"         NUMBER(22,7),
    "FILE_UPLOAD_ID"              NUMBER(10,0),
    "ETL_RUN_ID"                  NUMBER(10,0),
    "INTEGRATION_ID"              VARCHAR2(255 BYTE),
    "RECORD_STATUS"               VARCHAR2(50 BYTE),
    "CREATED_DT"                  DATE,
    "LAST_UPDATED_DT"             DATE,
    "CREATED_BY"                  VARCHAR2(80 BYTE),
    "LAST_UPDATED_BY"             VARCHAR2(80 BYTE),
    "STATUS_MESSAGE"              VARCHAR2(800 BYTE)
  );
--------------------------------------------------------
--  DDL for Index NR_MFMA_STG_U1
--------------------------------------------------------
CREATE UNIQUE INDEX "NR_MFMA_STG_U1" ON "NR_MFMA_STG"
  (
    "INTEGRATION_ID"
  )
  ;
