--------------------------------------------------------
--  DDL for Table NR_FPM_F
--------------------------------------------------------

DROP TABLE NR_FPM_F;


  CREATE TABLE "BIAPPS"."NR_FPM_F" 
   (	"PERIOD_END_DT_WID" NUMBER, 
	"SNAPSHOT_DT_WID" NUMBER, 
	"PROJECT_WID" NUMBER(10,0), 
	"BEGBALANCE_AFC_ALL_PHASES" NUMBER(22,7), 
	"BEGBALANCE_COWD_PTD" NUMBER(22,7), 
	"FY_CURRENT_RF" NUMBER(22,7), 
	"FY_BUDGET" NUMBER(22,7), 
	"FY_VARIANCE" NUMBER(22,7), 
	"FY_UNALLOCATED" NUMBER(22,7), 
	"FY_PLANNED_SLIPPAGE_TO_MAX_EFF" NUMBER(22,7), 
	"FY_SLIPPAGE_DUE_TO_3RD_PRTY" NUMBER(22,7), 
	"FY_UNPLANNED_SLIPPAGE" NUMBER(22,7), 
	"FY_WORK_REPRIOR_CTRL_FY" NUMBER(22,7), 
	"FY_WORK_BRT_FWD_INTO_CP5" NUMBER(22,7), 
	"FY_WORK_DEFERRED_OUT_OF_CP5" NUMBER(22,7), 
	"FY_INCREASED_SCOPE_RAB_APPRVD" NUMBER(22,7), 
	"FY_SCOPE_FPM" NUMBER(22,7), 
	"FY_SCOPE_FPM_2" NUMBER(22,7), 
	"FY_COST_FPM" NUMBER(22,7), 
	"YTD_ANALYSIS_CURRENT_RF" NUMBER(22,7), 
	"YTD_ANALYSIS_BUDGET" NUMBER(22,7), 
	"YTD_ANALYSIS_VARIANCE" NUMBER(22,7), 
	"YTD_ANALYSIS_UNALLOCATED" NUMBER(22,7), 
	"YTD_ANALYSIS_PLN_SLIP_MAX_EFF" NUMBER(22,7), 
	"YTD_ANALYSIS_SLIP_3RD_PRTY" NUMBER(22,7), 
	"YTD_ANALYSIS_UNPLANNED_SLIP" NUMBER(22,7), 
	"YTD_ANALYSIS_WRK_REPRIO_CP_YR" NUMBER(22,7), 
	"YTD_ANALYSIS_WRK_BRT_FWD_CP5" NUMBER(22,7), 
	"YTD_ANALYSIS_WORK_DEF_OUT_CP5" NUMBER(22,7), 
	"YTD_ANALYSIS_INCR_SCP_RAB_APPR" NUMBER(22,7), 
	"YTD_ANALYSIS_SCOPE_FPM" NUMBER(22,7), 
	"YTD_ANALYSIS_SCOPE_FPM_2" NUMBER(22,7), 
	"YTD_ANALYSIS_COST_FPM" NUMBER(22,7), 
	"PERIOD_CURRENT_RF" NUMBER(22,7), 
	"PERIOD_BUDGET" NUMBER(22,7), 
	"PERIOD_VARIANCE" NUMBER(22,7), 
	"PERIOD_TO_BE_ALLOCATED" NUMBER(22,7), 
	"PERIOD_PLANNED_SLIP_TO_MAX_EFF" NUMBER(22,7), 
	"PERIOD_SLIP_DUE_TO_3RD_PRTY" NUMBER(22,7), 
	"PERIOD_UNPLANNED_SLIPPAGE" NUMBER(22,7), 
	"PERIOD_WORK_REPRIO_CP_FY" NUMBER(22,7), 
	"PERIOD_WORK_BRT_FWD_INTO_CP5" NUMBER(22,7), 
	"PERIOD_WRK_DEFER_OUT_CP5" NUMBER(22,7), 
	"PERIOD_INCR_SCP_RAB_APPR" NUMBER(22,7), 
	"PERIOD_SCOPE_FPM" NUMBER(22,7), 
	"PERIOD_SCOPE_FPM_2" NUMBER(22,7), 
	"PERIOD_COST_FPM" NUMBER(22,7)
   ) ;
   
   
   
   --------------------------------------------------------
--  DDL for Table NR_FPM_STG
--------------------------------------------------------

  CREATE TABLE "BIAPPS"."NR_FPM_STG" 
   (	"PERIOD" NUMBER(10,0), 
	"YEAR" NUMBER(4,0), 
	"PROJECT_NUMBER" VARCHAR2(50 BYTE), 
	"PROJECT_DESCRIPTION" VARCHAR2(500 BYTE), 
	"REGION" VARCHAR2(150 BYTE), 
	"CATEGORY" VARCHAR2(12 BYTE), 
	"BEGBALANCE_AFC_ALL_PHASES" NUMBER(22,7), 
	"BEGBALANCE_COWD_PTD" NUMBER(22,7), 
	"FY_CURRENT_RF" NUMBER(22,7), 
	"FY_BUDGET" NUMBER(22,7), 
	"FY_VARIANCE" NUMBER(22,7), 
	"FY_UNALLOCATED" NUMBER(22,7), 
	"FY_PLANNED_SLIPPAGE_TO_MAX_EFF" NUMBER(22,7), 
	"FY_SLIPPAGE_DUE_TO_3RD_PRTY" NUMBER(22,7), 
	"FY_UNPLANNED_SLIPPAGE" NUMBER(22,7), 
	"FY_WORK_REPRIOR_CTRL_FY" NUMBER(22,7), 
	"FY_WORK_BRT_FWD_INTO_CP5" NUMBER(22,7), 
	"FY_WORK_DEFERRED_OUT_OF_CP5" NUMBER(22,7), 
	"FY_INCREASED_SCOPE_RAB_APPRVD" NUMBER(22,7), 
	"FY_SCOPE_FPM" NUMBER(22,7), 
	"FY_SCOPE_FPM_2" NUMBER(22,7), 
	"FY_COST_FPM" NUMBER(22,7), 
	"YTD_ANALYSIS_CURRENT_RF" NUMBER(22,7), 
	"YTD_ANALYSIS_BUDGET" NUMBER(22,7), 
	"YTD_ANALYSIS_VARIANCE" NUMBER(22,7), 
	"YTD_ANALYSIS_UNALLOCATED" NUMBER(22,7), 
	"YTD_ANALYSIS_PLN_SLIP_MAX_EFF" NUMBER(22,7), 
	"YTD_ANALYSIS_SLIP_3RD_PRTY" NUMBER(22,7), 
	"YTD_ANALYSIS_UNPLANNED_SLIP" NUMBER(22,7), 
	"YTD_ANALYSIS_WRK_REPRIO_CP_YR" NUMBER(22,7), 
	"YTD_ANALYSIS_WRK_BRT_FWD_CP5" NUMBER(22,7), 
	"YTD_ANALYSIS_WORK_DEF_OUT_CP5" NUMBER(22,7), 
	"YTD_ANALYSIS_INCR_SCP_RAB_APPR" NUMBER(22,7), 
	"YTD_ANALYSIS_SCOPE_FPM" NUMBER(22,7), 
	"YTD_ANALYSIS_SCOPE_FPM_2" NUMBER(22,7), 
	"YTD_ANALYSIS_COST_FPM" NUMBER(22,7), 
	"PERIOD_CURRENT_RF" NUMBER(22,7), 
	"PERIOD_BUDGET" NUMBER(22,7), 
	"PERIOD_VARIANCE" NUMBER(22,7), 
	"PERIOD_TO_BE_ALLOCATED" NUMBER(22,7), 
	"PERIOD_PLANNED_SLIP_TO_MAX_EFF" NUMBER(22,7), 
	"PERIOD_SLIP_DUE_TO_3RD_PRTY" NUMBER(22,7), 
	"PERIOD_UNPLANNED_SLIPPAGE" NUMBER(22,7), 
	"PERIOD_WORK_REPRIO_CP_FY" NUMBER(22,7), 
	"PERIOD_WORK_BRT_FWD_INTO_CP5" NUMBER(22,7), 
	"PERIOD_WRK_DEFER_OUT_CP5" NUMBER(22,7), 
	"PERIOD_INCR_SCP_RAB_APPR" NUMBER(22,7), 
	"PERIOD_SCOPE_FPM" NUMBER(22,7), 
	"PERIOD_SCOPE_FPM_2" NUMBER(22,7), 
	"PERIOD_COST_FPM" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BIDATA" ;

   
   
   
   